version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=user
#      - MONGO_INITDB_ROOT_PASSWORD=pass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb


volumes:
  mongodata:

networks:
  default:
    name: mongodb_network

